General:
  project_name: Test
  first_name: TestName
  last_name: TestLastName
  location: Test/Waw

Power_user:
  power_user: poweruser
  power_user_password:

Wireless_network:
  ssid_name: NameSSID
  ssid_password: Test1234
  ssid_encryption: WPA
  hidden: False

Wireless_guest_network:
  ssid_name: Deco Home_Guest
  ssid_password: Test1234
  ssid_encryption: WPA
  hidden: False